config/routes.rb
Financialcontrol::Application.routes.draw do
	resources :payment_methods

  resources :categories

  resources :transactions

  resources :clients do
		collection do
			get 'signup'
		end
		member do
			get 'login'
			get 'logout'
			get 'change_pw'
			get 'change'
			get 'trans'
			get 'report'
			get 'specific_t'
			get 'specific_period'
			get 'specific_values'
			get 'specific_category'
		end
  end

	root :to => 'clients#index'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :email, :name, :password

	validates_presence_of :name, :message => "must be given!"
	validate :email_must_be_valid
	validates_uniqueness_of :email, :message => "already registered!"
	validates_length_of :password, :minimum => 4, :message => "must have at least 4 characters!"

	private
	def email_must_be_valid
		errors.add("email", "e-mail must be in a valid format!") unless email =~ /\w+@(((gmail|hotmail|quantumtecnologia)\.com)|yahoo.com.br)\z/
	end

	has_many :transactions

end

app/controllers/clients_controller.rb
#encoding: utf-8

class ClientsController < ApplicationController
	helper_method :table_arranging
	helper_method :transactions_report
	helper_method :calculate_percentage
	helper_method :round_to_two_decimals

	def table_arranging
		@client = Client.find(params[:id])
		spec = params[:spec]
		if spec
			return @client.transactions.where(["YEAR(datetime) = ? AND MONTH(datetime) = ?", spec[:year], spec[:month]])
		else
			return nil
		end
	end

	def transactions_report
		@client = Client.find(params[:id])
		from = params[:old]
		values = params[:values]
		if from
			to = params[:new]
			beggining = DateTime.new(from[:year].to_i, from[:month].to_i, from[:day].to_i, from[:hours].to_i, from[:minutes].to_i)
			ending = DateTime.new(to[:year].to_i, to[:month].to_i, to[:day].to_i, to[:hours].to_i, to[:minutes].to_i)
			return @client.transactions.where(["datetime >= ? AND datetime <= ?", beggining, ending])
		elsif values
			return @client.transactions.where(["value >= ? AND value <= ?", values[:min].to_f, values[:max].to_f])
		else
			category = Category.where(["name = ?", params[:category_name].tr("*", " ")]).first
			return @client.transactions.where(["category_id = ?", category.id])
		end
	end

	def calculate_percentage(x, y)
		total = x + y
		return (x.to_f/total)*100
	end

	def round_to_two_decimals(n)
		return (n*100).to_i/100.0
	end

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])
		@client.logged = false
    if @client.save
      redirect_to signup_clients_path, notice: 'Client was successfully created!'
    else
      render action: "new"
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])		
    if @client.update_attributes(params[:client])
      redirect_to @client, notice: 'Client was successfully updated!'
    else
      render action: "edit"
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_url
  end

	def signup
	end

	def login
		in_client = params[:in_client]
		@client = Client.where(["email = ?", in_client[:email]]).first
		if @client
			if in_client[:password] == @client.password
				@client.logged = true
				@client.save
				redirect_to @client, notice: 'Logged successfully!'
			else
				redirect_to signup_clients_path, notice: 'Wrong password!'
			end
		else
			redirect_to signup_clients_path, notice: 'This e-mail is not registered!'
		end
	end

	def logout
		@client = Client.find(params[:id])
		@client.logged = false
		@client.save
		redirect_to clients_path, notice: 'Succesfully logged out!'
	end

	def change_pw
		@client = Client.find(params[:id])
		if !@client.logged
			redirect_to @client, notice: 'Not logged in!'
		end
	end

  def change
    @client = Client.find(params[:id])
		passwords = params[:pw]
		if @client.password == passwords[:old] && passwords[:new] == passwords[:confirm]
		  @client.password = passwords[:new]
			if @client.save
		  	redirect_to @client, notice: 'Password was successfully changed!'
			else
				render action: "change_pw"
			end
		else
			redirect_to @client, notice: 'Wrong password was given!'
		end
  end

	def trans
		@client = Client.find(params[:id])
		if !@client.logged
			redirect_to @client, notice: 'Not logged in!'
		end
	end

	def report
		@client = Client.find(params[:id])
	end

	def specific_t
    @client = Client.find(params[:id])
	end

	def specific_period
    @client = Client.find(params[:id])
	end

	def specific_values
    @client = Client.find(params[:id])
	end

	def specific_category
    @client = Client.find(params[:id])
	end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'E-mail' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password, :type => "password" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/change_pw.html.erb
<h1>Changing Password</h1>

<form action='change'>

	<% if @client.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@client.errors.count, "error") %> prohibited this password from being updated:</h2>

		  <ul>
		  <% @client.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	<% end %>

	<b>Old Password:</b></br>
	<input type='password' name='pw[old]'/></br>

  <b>New Password:</b></br>
	<input type='password' name='pw[new]'/></br>

  <b>Confirm new Password:</b></br>
	<input type='password' name='pw[confirm]'/></br></br>

	<input type='submit' value='Change Password'/>

</form>

</br>
<%= link_to 'Back', @client %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %>
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financial Control Application</title>
    <style type="text/css" media="screen">
      body {
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #f0f0f0;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #333;
      }

      h1 {
        font-size: 28px;
        color: #000;
      }

      a  {color: #03c}
      a:hover {
        background-color: #03c;
        color: white;
        text-decoration: none;
      }


      #page {
        background-color: #f0f0f0;
        width: 750px;
        margin: 0;
        margin-left: auto;
        margin-right: auto;
      }

      #content {
        float: left;
        background-color: white;
        border: 3px solid #aaa;
        border-top: none;
        padding: 25px;
        width: 500px;
      }

      #sidebar {
        float: right;
        width: 175px;
      }

      #footer {
        clear: both;
      }

      #header, #about, #getting-started {
        padding-left: 75px;
        padding-right: 30px;
      }


      #header {
        background-image: url("assets/cifrao.jpg");
        background-repeat: no-repeat;
        background-position: top left;
        height: 64px;
      }
      #header h1, #header h2 {margin: 0}
      #header h2 {
        color: #888;
        font-weight: normal;
        font-size: 16px;
      }


      #about h3 {
        margin: 0;
        margin-bottom: 10px;
        font-size: 14px;
      }

      #about-content {
        background-color: #ffd;
        border: 1px solid #fc0;
        margin-left: -55px;
        margin-right: -10px;
      }
      #about-content table {
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 11px;
        border-collapse: collapse;
      }
      #about-content td {
        padding: 10px;
        padding-top: 3px;
        padding-bottom: 3px;
      }
      #about-content td.name  {color: #555}
      #about-content td.value {color: #000}

      #about-content ul {
        padding: 0;
        list-style-type: none;
      }

      #about-content.failure {
        background-color: #fcc;
        border: 1px solid #f00;
      }
      #about-content.failure p {
        margin: 0;
        padding: 10px;
      }


      #getting-started {
        border-top: 1px solid #ccc;
        margin-top: 25px;
        padding-top: 15px;
      }
      #getting-started h1 {
        margin: 0;
        font-size: 20px;
      }
      #getting-started h2 {
        margin: 0;
        font-size: 14px;
        font-weight: normal;
        color: #333;
        margin-bottom: 25px;
      }
      #getting-started ol {
        margin-left: 0;
        padding-left: 0;
      }
      #getting-started li {
        font-size: 18px;
        color: #888;
        margin-bottom: 25px;
      }
      #getting-started li h2 {
        margin: 0;
        font-weight: normal;
        font-size: 18px;
        color: #333;
      }
      #getting-started li p {
        color: #555;
        font-size: 13px;
      }


      #sidebar ul {
        margin-left: 0;
        padding-left: 0;
      }
      #sidebar ul h3 {
        margin-top: 25px;
        font-size: 16px;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
      }
      #sidebar li {
        list-style-type: none;
      }
      #sidebar ul.links li {
        margin-bottom: 5px;
      }

      .filename {
        font-style: italic;
      }
    </style>
  </head>
  <body>
    <div id="page">
      <div id="content">
        <div id="header">
          <h1>Welcome to FCA!</h1></br>
          <h2>Keep track of all your financial transactions in Financial Control Application!</h2>
        </div>

        <div id="getting-started">

          <ol>
            <li>
              <h2>Check every transaction made until the present day</h2>
            </li>

            <li>
              <h2>See only transactions in specific categories</h2>
            </li>

            <li>
              <h2>See transactions which were made in the wanted period (since the last month, in the last year etc)</h2>
            </li>

            <li>
              <h2>Add comments in whichever transactions you wish, and avoid forgetting why they are there!</h2>
            </li>

            <li>
							<h2>Already have an account? <%= link_to 'Sign up!', signup_clients_path %></h2>
            </li>
						<li>	
							<h2>If not, <%= link_to 'Register now!', new_client_path %></h2>
						</li>
          </ol>
        </div>
      </div>

      <div id="footer">&nbsp;</div>
    </div>
  </body>
</html>

app/views/clients/new.html.erb
<h1>Registering...</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/report.html.erb
<p id="notice"><%= notice %></p>

<% transactions = transactions_report %>

<table border="3">
  <tr>
    <th>Value</th>
    <th>Occurred at</th>
    <th>Type</th>
    <th>Category</th>
  </tr>

<% transactions.each do |transaction| %>
	<tr>
		<td>$<%= transaction.value %></td>
		<td><%= transaction.datetime %></td>
		<td><% if transaction.credit %>
					CREDIT
				<% else %>
					DEBIT
				<% end %></td>
		<td><%= transaction.category.name %></td>
		<td><%= link_to 'Show', transaction %></td>
		<td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
	</tr>
<% end %>

</table>
</br>

<b>Total spent in these transactions:</b> $<%= transactions.sum(:value) %></br>
<b>Average spent in these transactions:</b> <%= round_to_two_decimals(transactions.average(:value)) %></br>
<% credit_count = (transactions.where(["credit = ?", true])).count(:credit) %>
<% debit_count = (transactions.where(["credit = ?", false])).count(:credit) %>
<b>Percentage of credit transactions:</b> <%= round_to_two_decimals(calculate_percentage(credit_count, debit_count)) %>%</br>
<b>Percentage of debit transactions:</b> <%= round_to_two_decimals(calculate_percentage(debit_count, credit_count)) %>%</br>

</br>

<%= link_to "See all transactions", trans_client_path %>
</br></br>
<%= link_to 'See transactions from a specific month', specific_t_client_path %>
</br></br>
<%= link_to 'Generate report for transactions in specific period', specific_period_client_path %>
</br></br>
<%= link_to 'Generate report for transactions with specific values range', specific_values_client_path %>
</br></br>
<%= link_to 'Generate report for transactions from a specific category', specific_category_client_path %>
</br></br>
<%= link_to "Add transaction", :controller => "transactions",
																						:action => "new",
																						:client => @client %>
</br></br>
<%= link_to 'Back', @client %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Logged?</b>
  <% if @client.logged %>
			YES
  <% else %>
			NO
	<% end %>
</p>

<%= link_to "See transactions", trans_client_path(@client) %></br></br>

<%= link_to 'Change password', change_pw_client_path %>
<% if @client.logged %>
	| <%= link_to 'Log out', action: :logout %>
<% else %>
	| <%= link_to 'Sign in', action: :signup %>
  | <%= link_to 'Back', clients_path %>
<% end %>
</br></br>
<% if @client.email == 'admin@quantumtecnologia.com' && @client.logged %>
	<%= link_to 'Browse categories', categories_path %>
<% end %>

app/views/clients/signup.html.erb
<p id="notice"><%= notice %></p>

<h1>Signing up</h1>

<form action='/clients/signup/login'>
	<table>
		<tr>
			<td>E-mail:</td>
			<td><input type='text' name='in_client[email]'/></td>
		</tr>
		<tr>
			</br>
			<td>Password:</td>
			<td><input type='password' name='in_client[password]'/></td>
		</tr>
	<table>
	</br>
	<input type='submit' value='Log In'/>
</form>

</br></br>
<%= link_to 'Back', clients_path %>

app/views/clients/specific_category.html.erb
<p id="notice"><%= notice %></p>

<form action='report'>
	<b>Category: </b>
	<select name='category_name'>
		<% for c in Category.all %>
			<option value= <%= c.name.tr(" ", "*") %>> <%= c.name %> </option>
		<% end %>
	</select>
	<input type='submit' value='Generate'/>
</form>

</br>
<%= link_to 'Back', trans_client_path %>

app/views/clients/specific_period.html.erb
<form action='report'>
<b>From --- </b>

<b>Year: </b>
<select name='old[year]'>
	<% for i in ((Time.now.year - 100)..Time.now.year).to_a.reverse %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Month: </b>
<select name='old[month]'>
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select>

<b>Day: </b>
<select name='old[day]'>
	<% for i in (1..31) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Hours: </b>
<select name='old[hours]'>
	<% for i in (0..23) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Minutes: </b>
<select name='old[minutes]'>
	<% for i in (0..59) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>
</br></br>


<b>To -------- </b>

<b>Year: </b>
<select name='new[year]'>
	<% for i in ((Time.now.year - 100)..Time.now.year).to_a.reverse %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Month: </b>
<select name='new[month]'>
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select>

<b>Day: </b>
<select name='new[day]'>
	<% for i in (1..31) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Hours: </b>
<select name='new[hours]'>
	<% for i in (0..23) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

<b>Minutes: </b>
<select name='new[minutes]'>
	<% for i in (0..59) %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select>

</br></br>
<input type='submit' value='Generate'/>
</form>

</br>
<%= link_to 'Back', trans_client_path %>

app/views/clients/specific_t.html.erb
<form action='trans'>
<b>Month:</b>
<select name='spec[month]'>
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select></br></br>
<b>Year:</b>
<select name='spec[year]'>
	<% for i in ((Time.now.year - 100)..Time.now.year).to_a.reverse %>	
  	<option value= <%= i %> > <%= i %> </option>
	<% end %>
</select></br></br>
<input type='submit' value='Arrange'/>
</form>

</br>
<%= link_to 'Back', trans_client_path %>

app/views/clients/specific_values.html.erb
<p id="notice"><%= notice %></p>

<form action='report'>
	Minimum value: <input type='text' name='values[min]'/>
	Maximum value: <input type='text' name='values[max]'/>
	<input type='submit' value='Generate'/>
</form>

</br>
<%= link_to 'Back', trans_client_path %>

app/views/clients/trans.html.erb
<p id="notice"><%= notice %></p>

<% specifics = table_arranging %>

<table border="3">
<% if !specifics %>

  <tr>
    <th>Value</th>
    <th>Occurred at</th>
    <th>Type</th>
	  <th>Category</th>
  </tr>

	<% @client.transactions.each do |transaction| %>
		<tr>
			<td>$<%= transaction.value %></td>
			<td><%= transaction.datetime %></td>
			<td><% if transaction.credit %>
						CREDIT
					<% else %>
						DEBIT
					<% end %></td>
			<td><%= transaction.category.name %></td>
			<td><%= link_to 'Show', transaction %></td>
			<td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
	<% end %>

<% else %>
	<% transactions = specifics.order(:category_id).order(:datetime) %>
	<% previous = nil %>

	<% transactions.each do |transaction| %>
		<% if !previous || (previous && (previous.category.name != transaction.category.name)) %>
		</table>
		<br>
			<td><b>Category:</b> <%= transaction.category.name %></td>
		</br></br>
		<table border="3">
			<tr>
				<th>Value</th>
				<th>Occurred at</th>
				<th>Type</th>
			</tr>
		<% end %>
		<% previous = transaction %>
		<tr>
			<td>$<%= transaction.value %></td>
			<td><%= transaction.datetime %></td>
			<td><% if transaction.credit %>
						CREDIT
					<% else %>
						DEBIT
					<% end %></td>
			<td><%= link_to 'Show', transaction %></td>
			<td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
	<% end %>

<% end %>
</table>

<% if @client.transactions.empty? %>
	<h4>You don't have registered transactions!</h4>
<% end %>
</br>

<%= link_to "See all transactions", trans_client_path %>
</br></br>
<%= link_to 'See transactions from a specific month', specific_t_client_path %>
</br></br>
<%= link_to 'Generate report for transactions in specific period', specific_period_client_path %>
</br></br>
<%= link_to 'Generate report for transactions with specific values range', specific_values_client_path %>
</br></br>
<%= link_to 'Generate report for transactions from a specific category', specific_category_client_path %>
</br></br>
<%= link_to "Add transaction", :controller => "transactions",
																						:action => "new",
																						:client => @client %>
</br></br>
<%= link_to 'Back', @client %>