config/routes.rb
Financialcontrol::Application.routes.draw do
	resources :payment_methods

  resources :categories

  resources :transactions

  resources :clients do
		collection do
			get 'signup'
		end
		member do
			get 'login'
			get 'logout'
			get 'change_pw'
			get 'change'
			get 'trans'
			get 'report'
			get 'specific_t'
			get 'specific_period'
			get 'specific_values'
			get 'specific_category'
		end
  end

	root :to => 'clients#index'
  match ':controller(/:action(/:id))(.:format)'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :description

	validates_presence_of :name, :message => "must be given!"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table border="2">
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% admin = Client.where(["email = ?", 'admin@quantumtecnologia.com']).first %>
<%= link_to 'New Category', new_category_path %> | 
<%= link_to 'Back', client_path(admin) %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>

<%= link_to "Add transaction", :controller => "transactions",
																						:action => "new",
																						:category => @category %>
</br></br>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>