config/routes.rb
Financialcontrol::Application.routes.draw do
	resources :payment_methods

  resources :categories

  resources :transactions

  resources :clients do
		collection do
			get 'signup'
		end
		member do
			get 'login'
			get 'logout'
			get 'change_pw'
			get 'change'
			get 'trans'
			get 'report'
			get 'specific_t'
			get 'specific_period'
			get 'specific_values'
			get 'specific_category'
		end
  end

	root :to => 'clients#index'
  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

		if params[:client]
			@transaction.client = Client.find(params[:client])
		end
		if params[:category]
			@transaction.category = Category.find(params[:category])
		end
		if params[:payment_method]
			@transaction.payment_method = PaymentMethod.find(params[:payment_method])
		end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])
    if @transaction.save
			@transaction.datetime = @transaction.created_at
			@transaction.save
      redirect_to trans_client_path(@transaction.client), notice: 'Transaction was successfully created!'
    else
      render action: "new"
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
	# Transactions must never be updated!
  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update_attributes(params[:transaction])
      redirect_to @transaction, notice: 'Transaction was successfully updated!'
    else
      render action: "edit"
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to trans_client_path(@transaction.client), notice: 'Transaction was successfully erased!'
  end

	def write_obs
    @transaction = Transaction.find(params[:id])
	end

	def add_obs
    @transaction = Transaction.find(params[:id])
		obs = params['obs']
		if obs != ''
			@transaction.obs = obs
			@transaction.save
			notice = 'Observation added successfully!'
		else
			notice = 'Nothing was written!'
		end
		redirect_to trans_client_path, notice: notice
	end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
		<% if @transaction.client %>
			<%= f.hidden_field 'client_id' %>
		<% else %>
			<p><%= f.label :client_id %><br />
			<%= f.collection_select(:client_id,
				Client.order('name'),
				:id, :name, {:prompt => true}) %></p>
		<% end %>
  </div>
  <div class="field">
		<% if @transaction.category %>
			<%= f.hidden_field 'category_id' %>
		<% else %>
			<p><%= f.label :category_id %><br />
			<%= f.collection_select(:category_id,
				Category.order('name'),
				:id, :name, {:prompt => true}) %></p>
		<% end %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :credit %><br />
    <%= f.check_box :credit %>
  </div>
  <div class="field">
    <%= f.label 'Observation' %><br />
    <%= f.text_area :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_form_edit.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
		<%= f.hidden_field 'client_id' %>
  </div>
  <div class="field">
		<%= f.hidden_field 'category_id' %>
  </div>
  <div class="field">
		<%= f.hidden_field 'value' %>
  </div>
  <div class="field">
		<%= f.hidden_field 'credit' %>
  </div>
  <div class="field">
    <%= f.label 'Observation' %><br />
    <%= f.text_area :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', @transaction.client %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Datetime</th>
    <th>Credit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.value %></td>
    <td><%= transaction.datetime %></td>
    <td><%= transaction.credit %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<% if @transaction.client %>
<%= link_to 'Back', trans_client_path(@transaction.client) %>
<% else %>
<%= link_to 'Back', categories_path %>
<% end %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @transaction.value %>
</p>

<p>
  <b>Occurred at:</b>
  <%= @transaction.datetime %>
</p>

<p>
  <b>Type:</b>
	<% if @transaction.credit %>
		CREDIT
	<% else %>
		DEBIT
	<% end %>
</p>

<p>
  <b>Category:</b>
  <%= @transaction.category.name %>
</p>

<p>
  <b>Observation:</b>
  <%= @transaction.obs %>
</p>

<%= link_to 'Edit observation', edit_transaction_path %>

</br></br>
<%= link_to 'Back', @transaction.client %>